import type { Doctor, Patient, Appointment, MedicalRecord, VitalSigns } from "./app-context"

export const mockDoctors: Doctor[] = [
  {
    id: "d1",
    name: "Dra. Carolina Mendez",
    specialty: "Medicina General",
    avatar: "CM",
    rating: 4.9,
    reviewCount: 234,
    available: true,
    nextAvailable: "Hoy, 3:00 PM",
    experience: "12 anos",
    languages: ["Espanol", "Ingles"],
  },
  {
    id: "d2",
    name: "Dr. Andres Rivera",
    specialty: "Cardiologia",
    avatar: "AR",
    rating: 4.8,
    reviewCount: 189,
    available: true,
    nextAvailable: "Hoy, 4:30 PM",
    experience: "15 anos",
    languages: ["Espanol"],
  },
  {
    id: "d3",
    name: "Dra. Maria Torres",
    specialty: "Neumologia",
    avatar: "MT",
    rating: 4.7,
    reviewCount: 156,
    available: false,
    nextAvailable: "Manana, 9:00 AM",
    experience: "10 anos",
    languages: ["Espanol", "Portugues"],
  },
  {
    id: "d4",
    name: "Dr. Felipe Gutierrez",
    specialty: "Medicina Interna",
    avatar: "FG",
    rating: 4.9,
    reviewCount: 312,
    available: true,
    nextAvailable: "Hoy, 5:00 PM",
    experience: "18 anos",
    languages: ["Espanol", "Ingles", "Frances"],
  },
  {
    id: "d5",
    name: "Dra. Sofia Castillo",
    specialty: "Pediatria",
    avatar: "SC",
    rating: 4.8,
    reviewCount: 278,
    available: true,
    nextAvailable: "Hoy, 2:00 PM",
    experience: "8 anos",
    languages: ["Espanol"],
  },
]

export const mockPatients: Patient[] = [
  {
    id: "p1",
    name: "Juan Carlos Herrera",
    age: 45,
    gender: "Masculino",
    bloodType: "O+",
    allergies: ["Penicilina"],
    conditions: ["Hipertension", "Diabetes Tipo 2"],
    lastVisit: "2026-02-28",
  },
  {
    id: "p2",
    name: "Ana Maria Lopez",
    age: 32,
    gender: "Femenino",
    bloodType: "A+",
    allergies: [],
    conditions: ["Asma"],
    lastVisit: "2026-03-01",
  },
  {
    id: "p3",
    name: "Carlos Eduardo Perez",
    age: 58,
    gender: "Masculino",
    bloodType: "B-",
    allergies: ["Sulfa", "Ibuprofeno"],
    conditions: ["Arritmia cardiaca", "Hipotiroidismo"],
    lastVisit: "2026-02-25",
  },
  {
    id: "p4",
    name: "Laura Valentina Garcia",
    age: 28,
    gender: "Femenino",
    bloodType: "AB+",
    allergies: [],
    conditions: [],
    lastVisit: "2026-03-02",
  },
  {
    id: "p5",
    name: "Roberto Andres Martinez",
    age: 67,
    gender: "Masculino",
    bloodType: "O-",
    allergies: ["Aspirina"],
    conditions: ["EPOC", "Hipertension", "Insuficiencia renal"],
    lastVisit: "2026-02-20",
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: "a1",
    patientName: "Juan Carlos Herrera",
    doctorName: "Dra. Carolina Mendez",
    doctorSpecialty: "Medicina General",
    date: "2026-03-03",
    time: "3:00 PM",
    status: "scheduled",
    type: "virtual",
  },
  {
    id: "a2",
    patientName: "Ana Maria Lopez",
    doctorName: "Dr. Andres Rivera",
    doctorSpecialty: "Cardiologia",
    date: "2026-03-03",
    time: "4:30 PM",
    status: "scheduled",
    type: "virtual",
  },
  {
    id: "a3",
    patientName: "Carlos Eduardo Perez",
    doctorName: "Dra. Maria Torres",
    doctorSpecialty: "Neumologia",
    date: "2026-03-02",
    time: "10:00 AM",
    status: "completed",
    type: "virtual",
    notes: "Control de EPOC. Paciente estable.",
  },
  {
    id: "a4",
    patientName: "Laura Valentina Garcia",
    doctorName: "Dra. Sofia Castillo",
    doctorSpecialty: "Pediatria",
    date: "2026-03-04",
    time: "9:00 AM",
    status: "scheduled",
    type: "in-person",
  },
  {
    id: "a5",
    patientName: "Roberto Andres Martinez",
    doctorName: "Dr. Felipe Gutierrez",
    doctorSpecialty: "Medicina Interna",
    date: "2026-03-01",
    time: "11:00 AM",
    status: "completed",
    type: "virtual",
    notes: "Revision general. Ajuste de medicacion.",
  },
]

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: "r1",
    date: "2026-03-01",
    doctorName: "Dr. Felipe Gutierrez",
    diagnosis: "Hipertension arterial controlada",
    treatment: "Continuacion de Losartan 50mg diario",
    prescriptions: ["Losartan 50mg", "Metformina 850mg"],
    vitals: {
      heartRate: 78,
      spo2: 97,
      respiratoryRate: 16,
      bloodPressure: "130/85",
      temperature: 36.5,
      timestamp: new Date("2026-03-01T11:00:00"),
    },
    notes: "Paciente refiere sentirse bien. Presion arterial dentro de parametros aceptables. Se recomienda continuar con dieta baja en sodio y ejercicio moderado.",
  },
  {
    id: "r2",
    date: "2026-02-15",
    doctorName: "Dr. Andres Rivera",
    diagnosis: "Control cardiologico de rutina",
    treatment: "Sin cambios en medicacion actual",
    prescriptions: ["Atorvastatina 20mg"],
    vitals: {
      heartRate: 72,
      spo2: 98,
      respiratoryRate: 14,
      bloodPressure: "125/80",
      temperature: 36.7,
      timestamp: new Date("2026-02-15T09:30:00"),
    },
    notes: "Electrocardiograma normal. Ritmo sinusal. No se evidencian alteraciones significativas.",
  },
  {
    id: "r3",
    date: "2026-01-20",
    doctorName: "Dra. Carolina Mendez",
    diagnosis: "Infeccion respiratoria aguda",
    treatment: "Amoxicilina 500mg cada 8 horas por 7 dias",
    prescriptions: ["Amoxicilina 500mg", "Acetaminofen 500mg", "Loratadina 10mg"],
    vitals: {
      heartRate: 88,
      spo2: 95,
      respiratoryRate: 20,
      bloodPressure: "120/78",
      temperature: 38.2,
      timestamp: new Date("2026-01-20T14:00:00"),
    },
    notes: "Paciente con sintomas de tos productiva, fiebre y congestion nasal desde hace 3 dias. Se inicia tratamiento antibiotico.",
  },
]

export const mockVitalsHistory: VitalSigns[] = [
  { heartRate: 78, spo2: 97, respiratoryRate: 16, bloodPressure: "130/85", temperature: 36.5, timestamp: new Date("2026-03-01T11:00:00") },
  { heartRate: 72, spo2: 98, respiratoryRate: 14, bloodPressure: "125/80", temperature: 36.7, timestamp: new Date("2026-02-15T09:30:00") },
  { heartRate: 88, spo2: 95, respiratoryRate: 20, bloodPressure: "120/78", temperature: 38.2, timestamp: new Date("2026-01-20T14:00:00") },
  { heartRate: 75, spo2: 98, respiratoryRate: 15, bloodPressure: "128/82", temperature: 36.6, timestamp: new Date("2025-12-10T10:00:00") },
  { heartRate: 80, spo2: 96, respiratoryRate: 17, bloodPressure: "135/88", temperature: 36.4, timestamp: new Date("2025-11-05T16:00:00") },
]

export const doctorSchedule = [
  { time: "08:00", patient: null, available: true },
  { time: "08:30", patient: "Juan Carlos Herrera", available: false },
  { time: "09:00", patient: "Ana Maria Lopez", available: false },
  { time: "09:30", patient: null, available: true },
  { time: "10:00", patient: null, available: true },
  { time: "10:30", patient: "Carlos Eduardo Perez", available: false },
  { time: "11:00", patient: null, available: true },
  { time: "11:30", patient: null, available: true },
  { time: "14:00", patient: "Laura Valentina Garcia", available: false },
  { time: "14:30", patient: null, available: true },
  { time: "15:00", patient: "Roberto Andres Martinez", available: false },
  { time: "15:30", patient: null, available: true },
  { time: "16:00", patient: null, available: true },
  { time: "16:30", patient: null, available: true },
]
